/*

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/
module derelict.opengl.extensions.arb_m;

import derelict.opengl.types : usingContexts;
import derelict.opengl.extensions.internal;

// ARB_multi_bind <-- Core in GL 4.4
enum ARB_multi_bind = "GL_ARB_multi_bind";
enum arbMultBindDecls =
q{
extern(System) @nogc nothrow {
    alias da_glBindBuffersBase = void function(GLenum,GLuint,GLsizei,const(GLuint)*);
    alias da_glBindBuffersRange = void function(GLenum,GLuint,GLsizei,const(GLuint)*,const(GLintptr)*,const(GLsizeiptr)*);
    alias da_glBindTextures = void function(GLuint,GLsizei,const(GLuint)*);
    alias da_glBindSamplers = void function(GLuint,GLsizei,const(GLuint)*);
    alias da_glBindImageTextures = void function(GLuint,GLsizei,const(GLuint)*);
    alias da_glBindVertexBuffers = void function(GLuint,GLsizei,const(GLuint)*,const(GLintptr)*,const(GLsizei)*);
}};

enum arbMultBindFuncs =
q{
    da_glBindBuffersBase glBindBuffersBase;
    da_glBindBuffersRange glBindBuffersRange;
    da_glBindTextures glBindTextures;
    da_glBindSamplers glBindSamplers;
    da_glBindImageTextures glBindImageTextures;
    da_glBindVertexBuffers glBindVertexBuffers;
};

enum arbMultBindLoaderImpl =
q{
    bindGLFunc(cast(void**)&glBindBuffersBase, "glBindBuffersBase");
    bindGLFunc(cast(void**)&glBindBuffersRange, "glBindBuffersRange");
    bindGLFunc(cast(void**)&glBindTextures, "glBindTextures");
    bindGLFunc(cast(void**)&glBindSamplers, "glBindSamplers");
    bindGLFunc(cast(void**)&glBindImageTextures, "glBindImageTextures");
    bindGLFunc(cast(void**)&glBindVertexBuffers, "glBindVertexBuffers");
};

enum arbMultBindLoader = makeLoader(ARB_multi_bind, arbMultBindLoaderImpl, "gl44");
static if(!usingContexts) enum arbMultBind = arbMultBindDecls ~ arbMultBindFuncs.makeGShared() ~ arbMultBindLoader;